# Nombre del workflow (aparece en la pestaña de Actions)
name: Prueba Pipeline

# Ejecuta este workflow cuando se haga push a la rama main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Usa una máquina virtual con Ubuntu

    steps:
      # Paso 1: Clona el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Inicia sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construye la imagen y la sube a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Usa el directorio raíz como contexto (donde está el Dockerfile)
          push: true  # Sube la imagen si se construye correctamente
          tags: mrharvyson/prueba:latest